export const data = [
  {
    id: 1,
    img:
      "https://img.favpng.com/25/7/23/computer-icons-user-profile-avatar-image-png-favpng-LFqDyLRhe3PBXM0sx2LufsGFU.jpg",
    name: "Korie Ocrevy",
    post: "Nuclear Power Engineer",
    email: "kocrevy0@thetimes.co.uk",
    city: "Krasnosilka",
    start: "09/23/2016",
    salary: "$23896.35",
    age: "33",
    experience: "1 year",
    status: "Professional",
  },
  {
    id: 2,
    img:
      "https://img.favpng.com/25/7/23/computer-icons-user-profile-avatar-image-png-favpng-LFqDyLRhe3PBXM0sx2LufsGFU.jpg",
    name: "Korie Ocrevy",
    post: "Nuclear Power Engineer",
    email: "kocrevy0@thetimes.co.uk",
    city: "Krasnosilka",
    start: "09/23/2016",
    salary: "$23896.35",
    age: "33",
    experience: "1 year",
    status: "Professional",
  },
  {
    id: 3,
    img:
      "https://img.favpng.com/25/7/23/computer-icons-user-profile-avatar-image-png-favpng-LFqDyLRhe3PBXM0sx2LufsGFU.jpg",
    name: "Korie Ocrevy",
    post: "Nuclear Power Engineer",
    email: "kocrevy0@thetimes.co.uk",
    city: "Krasnosilka",
    start: "09/23/2016",
    salary: "$23896.35",
    age: "33",
    experience: "1 year",
    status: "Professional",
  },
  {
    id: 4,
    img:
      "https://img.favpng.com/25/7/23/computer-icons-user-profile-avatar-image-png-favpng-LFqDyLRhe3PBXM0sx2LufsGFU.jpg",
    name: "Korie Ocrevy",
    post: "Nuclear Power Engineer",
    email: "kocrevy0@thetimes.co.uk",
    city: "Krasnosilka",
    start: "09/23/2016",
    salary: "$23896.35",
    age: "33",
    experience: "1 year",
    status: "Professional",
  },
  {
    id: 5,
    img:
      "https://img.favpng.com/25/7/23/computer-icons-user-profile-avatar-image-png-favpng-LFqDyLRhe3PBXM0sx2LufsGFU.jpg",
    name: "Korie Ocrevy",
    post: "Nuclear Power Engineer",
    email: "kocrevy0@thetimes.co.uk",
    city: "Krasnosilka",
    start: "09/23/2016",
    salary: "$23896.35",
    age: "33",
    experience: "1 year",
    status: "Professional",
  },
  {
    id: 6,
    img:
      "https://img.favpng.com/25/7/23/computer-icons-user-profile-avatar-image-png-favpng-LFqDyLRhe3PBXM0sx2LufsGFU.jpg",
    name: "Korie Ocrevy",
    post: "Nuclear Power Engineer",
    email: "kocrevy0@thetimes.co.uk",
    city: "Krasnosilka",
    start: "09/23/2016",
    salary: "$23896.35",
    age: "33",
    experience: "1 year",
    status: "Professional",
  },
  {
    id: 7,
    img:
      "https://img.favpng.com/25/7/23/computer-icons-user-profile-avatar-image-png-favpng-LFqDyLRhe3PBXM0sx2LufsGFU.jpg",
    name: "Korie Ocrevy",
    post: "Nuclear Power Engineer",
    email: "kocrevy0@thetimes.co.uk",
    city: "Krasnosilka",
    start: "09/23/2016",
    salary: "$23896.35",
    age: "33",
    experience: "1 year",
    status: "Professional",
  },
  {
    id: 8,
    img:
      "https://img.favpng.com/25/7/23/computer-icons-user-profile-avatar-image-png-favpng-LFqDyLRhe3PBXM0sx2LufsGFU.jpg",
    name: "Korie Ocrevy",
    post: "Nuclear Power Engineer",
    email: "kocrevy0@thetimes.co.uk",
    city: "Krasnosilka",
    start: "09/23/2016",
    salary: "$23896.35",
    age: "33",
    experience: "1 year",
    status: "Professional",
  },
  {
    id: 9,
    img:
      "https://img.favpng.com/25/7/23/computer-icons-user-profile-avatar-image-png-favpng-LFqDyLRhe3PBXM0sx2LufsGFU.jpg",
    name: "Korie Ocrevy",
    post: "Nuclear Power Engineer",
    email: "kocrevy0@thetimes.co.uk",
    city: "Krasnosilka",
    start: "09/23/2016",
    salary: "$23896.35",
    age: "33",
    experience: "1 year",
    status: "Professional",
  },
  {
    id: 10,
    img:
      "https://img.favpng.com/25/7/23/computer-icons-user-profile-avatar-image-png-favpng-LFqDyLRhe3PBXM0sx2LufsGFU.jpg",
    name: "Korie Ocrevy",
    post: "Nuclear Power Engineer",
    email: "kocrevy0@thetimes.co.uk",
    city: "Krasnosilka",
    start: "09/23/2016",
    salary: "$23896.35",
    age: "33",
    experience: "1 year",
    status: "Professional",
  },
];
