import {
  FiCalendar,
  FiMessageSquare,
  FiMail,
  FiCheckSquare,
  FiStar,
  FiUser,
  FiType,
  FiDroplet,
  FiEye,
  FiCreditCard,
  FiArchive,
  FiPlusCircle,
  FiLayout,
  FiCopy,
  FiPackage,
  FiCheckCircle,
  FiGrid,
  FiPieChart,
  FiMap,
  FiShield,
  FiMenu,
  FiEyeOff,
  FiLifeBuoy,
  FiFile,
  FiCircle,
} from "react-icons/fi";
import { BiShoppingBag } from "react-icons/bi";
import { RiArchiveDrawerLine } from "react-icons/ri";

export const logo = [
  {
    label: "Vuexy",
    icon:
      "https://pixinvent.com/demo/vuexy-vuejs-admin-dashboard-template/demo-1/img/logo.36f34a9f.svg",
  },
];

export const data = [
  {
    label: "APPS & PAGES",
    props: [
      {
        id: "1",
        name: "Email",
        urls: "/email/",
        icon: <FiMail />,
      },
      {
        id: "2",
        name: "Chat",
        urls: "/chat/",
        icon: <FiMessageSquare />,
      },
      {
        id: "3",
        name: "Todo",
        urls: "/Todo/",
        icon: <FiCheckSquare />,
      },
      {
        id: "4",
        name: "Calendar",
        urls: "/Calendar/",
        icon: <FiCalendar />,
      },
      {
        id: "5",
        name: "Invoice",
        urls: "/Invoice/",
        icon: <FiCheckSquare />,
        subItems: ["List", "Preview", "Edit", "Add"],
      },
      {
        id: "6",
        name: "eCommerce",
        urls: "/eCommerce/",
        icon: <BiShoppingBag />,
        subItems: ["List", "Preview", "Edit", "Add"],
      },
      {
        id: "7",
        name: "User",
        urls: "/User/",
        icon: <FiUser />,
        subItems: ["List", "Preview", "Edit", "Add"],
      },
      {
        id: "8",
        name: "Pages",
        urls: "/Pages/",
        icon: <FiCheckSquare />,
        subItems: ["List", "Preview", "Edit", "Add"],
      },
    ],
  },
  {
    label: "USER INTERFACE",
    props: [
      {
        id: "1",
        name: "Typography",
        urls: "/typography/",
        icon: <FiType />,
      },
      {
        id: "2",
        name: "Colors",
        urls: "/colors/",
        icon: <FiDroplet />,
      },
      {
        id: "3",
        name: "Feather",
        urls: "/feather/",
        icon: <FiEye />,
      },
      {
        id: "4",
        name: "Cards",
        urls: "/cards/",
        icon: <FiCreditCard />,
        subItems: [
          "Basic",
          "Advance",
          "Statistics",
          "Analytics",
          "Card Actions",
        ],
      },
      {
        id: "5",
        name: "Components",
        urls: "/components/",
        icon: <FiArchive />,
        subItems: [
          "Alert",
          "Aspect",
          "Avatar",
          "Badge",
          "Breadcrumb",
          "Button",
          "Button Group",
          "Button Toolbar",
          "Calendar",
          "Carousel",
          "Collapse",
          "Dropdown",
          "Embed",
          "Image",
          "List Group",
          "Media Objects",
          "Modal",
          "Nav",
          "Overlay",
          "Pagination",
          "Pagination New",
          "Pill",
          "Pill Badges",
          "Popover",
          "Progress",
          "Sidebar",
          "spinner",
          "Tab",
          "Time",
          "Timeline",
          "Toast",
          "Tooltip",
          "Eztensions",
          "Page Layouts",
        ],
      },
    ],
  },
  {
    label: "FORMS & TABLES",
    props: [
      {
        id: "1",
        name: "Form elements",
        urls: "/elements/",
        icon: <FiCopy />,
        subItems: [
          "Input",
          "Input Group",
          "Input Mask",
          "Texarea",
          "Auto Suggest",
          "CHeckbox",
          "Radio",
          "Switch",
          "Select",
          "Cue Select",
          "Spinbutton",
          "Sile Input",
          "File Input",
          "Quill Editor",
          "From Datepicker",
          "From Timepicker",
          "Date Time Picker",
          "Form Rating",
          "From Tag",
        ],
      },
      {
        id: "2",
        name: "Form Layout",
        urls: "/formlayout/",
        icon: <FiCopy />,
      },
      {
        id: "3",
        name: "Form Wizard",
        urls: "/wizard/",
        icon: <FiPackage />,
      },
      {
        id: "4",
        name: "Form Validation",
        urls: "/validation/",
        icon: <FiCheckCircle />,
      },
      {
        id: "5",
        name: "Form Repeater",
        urls: "/repeater/",
        icon: <FiGrid />,
      },
      {
        id: "6",
        name: "BS Table",
        urls: "/table/",
        icon: <FiPieChart />,
      },
      {
        id: "3",
        name: "Good Table",
        urls: "/goodtable/",
        icon: <FiMap />,
      },
    ],
  },
  {
    label: "CHARTS & MAPS",
    props: [
      {
        id: "1",
        name: "Charts",
        urls: "/charts/",
        icon: <FiPieChart />,
        subItems: ["Apex Chart", "CHartjs", "Echart"],
      },
      {
        id: "2",
        name: "Leaflet",
        urls: "/leaflet/",
        icon: <FiMap />,
      },
    ],
  },
  {
    label: "OTHERS",
    props: [
      {
        id: "1",
        name: "Access Control",
        urls: "/control/",
        icon: <FiShield />,
      },
      {
        id: "2",
        name: "Menu Levels",
        urls: "/menulevels/",
        icon: <FiMenu />,
        subItems: ["Menu Level 2.1", "Menu Level 2.2"],
      },
      {
        id: "3",
        name: "Disabled Menu",
        urls: "/disbaledmenu/",
        icon: <FiEyeOff />,
      },
      {
        id: "4",
        name: "Raise Support",
        urls: "/support/",
        icon: <FiLifeBuoy />,
      },
      {
        id: "5",
        name: "Documentation",
        urls: "/documentation/",
        icon: <FiFile />,
      },
    ],
  },
];
